export interface RegistryModule {
  slug: string;
  name: string;
  description: string;
  category?: string;
  enabled?: boolean;
  route?: string;
}

export const modules: RegistryModule[] = [
  {
    slug: "supergestor",
    name: "Supergestor",
    description: "Hub de IA para decisões operacionais e financeiras",
    category: "operations",
    enabled: true,
    route: "/supergestor",
  },
  {
    slug: "predictive-maintenance",
    name: "Manutenção Preditiva",
    description: "Previsões de manutenção por IA e risco de pneus",
    category: "maintenance",
    enabled: true,
    route: "/predictive-maintenance",
  },
  {
    slug: "drivers-management",
    name: "Gestão de Motoristas",
    description: "Cadastro, jornada, violações e histórico de viagens",
    category: "operations",
    enabled: true,
    route: "/drivers-management",
  },
  {
    slug: "approvals",
    name: "Aprovações",
    description: "Fluxo de aprovações operacionais e financeiras",
    category: "operations",
    enabled: true,
    route: "/approvals",
  },
  {
    slug: "logistics-kpi",
    name: "KPIs de Logística",
    description: "Indicadores de performance e custos por KM",
    category: "operations",
    enabled: true,
    route: "/logistics-kpi",
  },
  {
    slug: "bank-reconciliation",
    name: "Conciliação Bancária",
    description: "Importação e conciliação de extratos bancários",
    category: "finance",
    enabled: true,
    route: "/bank-reconciliation",
  },
  {
    slug: "cost-monitoring",
    name: "Monitoramento de Custos",
    description: "Acompanhamento de despesas e otimização de custo/km",
    category: "finance",
    enabled: true,
    route: "/cost-monitoring",
  },
  {
    slug: "iot",
    name: "IoT",
    description: "Telemetria de frota e sensores em tempo real",
    category: "iot",
    enabled: true,
    route: "/iot",
  },
  {
    slug: "permissions",
    name: "Permissões",
    description: "Perfis, papéis e autorização por módulo",
    category: "operations",
    enabled: true,
    route: "/permissions",
  },
  {
    slug: "developer",
    name: "Developer",
    description: "Ferramentas para dev, logs e diagnósticos",
    category: "dev",
    enabled: true,
    route: "/developer",
  },
  {
    slug: "reports",
    name: "Relatórios",
    description: "Relatórios executivos e financeiros",
    category: "business",
    enabled: true,
    route: "/reports",
  },
  {
    slug: "supergestor-ai",
    name: "SuperGestor AI",
    description: "Assistente de IA e Machine Learning avançado",
    category: "business",
    enabled: true,
    route: "/supergestor-ai",
  },
  {
    slug: "blockchain-tracking",
    name: "Blockchain & Rastreabilidade",
    description: "Rastreamento imutável e contratos inteligentes",
    category: "operations",
    enabled: true,
    route: "/blockchain-tracking",
  },
  {
    slug: "digital-twin",
    name: "Digital Twin da Frota",
    description: "Gêmeo digital em tempo real de cada veículo",
    category: "iot",
    enabled: true,
    route: "/digital-twin",
  },
  {
    slug: "esg-dashboard",
    name: "ESG & Sustentabilidade",
    description: "Dashboard de impacto ambiental, social e governança",
    category: "business",
    enabled: true,
    route: "/esg-dashboard",
  },
  {
    slug: "ai-route-optimization",
    name: "Otimização de Rotas IA",
    description: "Rotas otimizadas com Machine Learning",
    category: "operations",
    enabled: true,
    route: "/ai-route-optimization",
  },
  {
    slug: "cargo-marketplace",
    name: "Marketplace de Cargas",
    description: "Conecta embarcadores e transportadoras",
    category: "business",
    enabled: true,
    route: "/cargo-marketplace",
  },
  {
    slug: "advanced-analytics",
    name: "Analytics Avançado",
    description: "Big Data, ML e análise preditiva em tempo real",
    category: "business",
    enabled: true,
    route: "/advanced-analytics",
  },
  {
    slug: "consultoria-financeira-ia",
    name: "Consultoria Financeira IA",
    description: "Análise de risco financeiro com ML + recomendações priorizadas por ROI",
    category: "finance",
    enabled: true,
    route: "/consultoria-financeira-ia",
  },
  {
    slug: "analise-tributaria",
    name: "Análise Tributária Comparativa",
    description: "Lucro Real vs Presumido vs Simples | Projeção 1, 2 e 5 anos",
    category: "finance",
    enabled: true,
    route: "/analise-tributaria",
  },
  {
    slug: "app-motorista",
    name: "Super App Motorista",
    description: "Check-in + POD Digital + Checklist MOPP + Navegação",
    category: "operations",
    enabled: true,
    route: "/app-motorista",
  },
  {
    slug: "gestao-pops",
    name: "Gestão de POPs",
    description: "Procedimentos Operacionais Padrão - Conformidade SASSMAQ e controle de ocorrências",
    category: "maintenance",
    enabled: true,
    route: "/gestao-pops",
  },
  {
    slug: "auditoria-sassmaq",
    name: "Auditoria SASSMAQ/ISO",
    description: "Sistema de auditoria virtual com certificações SASSMAQ, ISO 9001/14001/45001",
    category: "maintenance",
    enabled: true,
    route: "/auditoria-sassmaq",
  },
];
