export interface RegistryModule {
  slug: string;
  name: string;
  description: string;
  category?: string;
  enabled?: boolean;
  route?: string;
}

export const modules: RegistryModule[] = [
  {
    slug: "supergestor",
    name: "Supergestor",
    description: "Hub de IA para decisões operacionais e financeiras",
    category: "operations",
    enabled: true,
    route: "/supergestor",
  },
  {
    slug: "predictive-maintenance",
    name: "Manutenção Preditiva",
    description: "Previsões de manutenção por IA e risco de pneus",
    category: "maintenance",
    enabled: true,
    route: "/predictive-maintenance",
  },
  {
    slug: "drivers-management",
    name: "Gestão de Motoristas",
    description: "Cadastro, jornada, violações e histórico de viagens",
    category: "operations",
    enabled: true,
    route: "/drivers-management",
  },
  {
    slug: "approvals",
    name: "Aprovações",
    description: "Fluxo de aprovações operacionais e financeiras",
    category: "operations",
    enabled: true,
    route: "/approvals",
  },
  {
    slug: "logistics-kpi",
    name: "KPIs de Logística",
    description: "Indicadores de performance e custos por KM",
    category: "operations",
    enabled: true,
    route: "/logistics-kpi",
  },
  {
    slug: "bank-reconciliation",
    name: "Conciliação Bancária",
    description: "Importação e conciliação de extratos bancários",
    category: "finance",
    enabled: true,
    route: "/bank-reconciliation",
  },
  {
    slug: "cost-monitoring",
    name: "Monitoramento de Custos",
    description: "Acompanhamento de despesas e otimização de custo/km",
    category: "finance",
    enabled: true,
    route: "/cost-monitoring",
  },
  {
    slug: "iot",
    name: "IoT",
    description: "Telemetria de frota e sensores em tempo real",
    category: "iot",
    enabled: true,
    route: "/iot",
  },
  {
    slug: "permissions",
    name: "Permissões",
    description: "Perfis, papéis e autorização por módulo",
    category: "operations",
    enabled: true,
    route: "/permissions",
  },
  {
    slug: "developer",
    name: "Developer",
    description: "Ferramentas para dev, logs e diagnósticos",
    category: "dev",
    enabled: true,
    route: "/developer",
  },
  {
    slug: "reports",
    name: "Relatórios",
    description: "Relatórios executivos e financeiros",
    category: "business",
    enabled: true,
    route: "/reports",
  },
  {
    slug: "supergestor-ai",
    name: "SuperGestor AI",
    description: "Assistente de IA e Machine Learning avançado",
    category: "business",
    enabled: true,
    route: "/supergestor-ai",
  },
  {
    slug: "blockchain-tracking",
    name: "Blockchain & Rastreabilidade",
    description: "Rastreamento imutável e contratos inteligentes",
    category: "operations",
    enabled: true,
    route: "/blockchain-tracking",
  },
  {
    slug: "digital-twin",
    name: "Digital Twin da Frota",
    description: "Gêmeo digital em tempo real de cada veículo",
    category: "iot",
    enabled: true,
    route: "/digital-twin",
  },
  {
    slug: "esg-dashboard",
    name: "ESG & Sustentabilidade",
    description: "Dashboard de impacto ambiental, social e governança",
    category: "business",
    enabled: true,
    route: "/esg-dashboard",
  },
  {
    slug: "ai-route-optimization",
    name: "Otimização de Rotas IA",
    description: "Rotas otimizadas com Machine Learning",
    category: "operations",
    enabled: true,
    route: "/ai-route-optimization",
  },
  {
    slug: "cargo-marketplace",
    name: "Marketplace de Cargas",
    description: "Conecta embarcadores e transportadoras",
    category: "business",
    enabled: true,
    route: "/cargo-marketplace",
  },
  {
    slug: "advanced-analytics",
    name: "Analytics Avançado",
    description: "Big Data, ML e análise preditiva em tempo real",
    category: "business",
    enabled: true,
    route: "/advanced-analytics",
  },
  {
    slug: "consultoria-financeira-ia",
    name: "Consultoria Financeira IA",
    description: "Análise de risco financeiro com ML + recomendações priorizadas por ROI",
    category: "finance",
    enabled: true,
    route: "/consultoria-financeira-ia",
  },
  {
    slug: "analise-tributaria",
    name: "Análise Tributária Comparativa",
    description: "Lucro Real vs Presumido vs Simples | Projeção 1, 2 e 5 anos",
    category: "finance",
    enabled: true,
    route: "/analise-tributaria",
  },
  {
    slug: "app-motorista",
    name: "Super App Motorista",
    description: "Check-in + POD Digital + Checklist MOPP + Navegação",
    category: "operations",
    enabled: true,
    route: "/app-motorista",
  },
  {
    slug: "gestao-pops",
    name: "Gestão de POPs",
    description: "Procedimentos Operacionais Padrão - Conformidade SASSMAQ e controle de ocorrências",
    category: "maintenance",
    enabled: true,
    route: "/gestao-pops",
  },
  {
    slug: "auditoria-sassmaq",
    name: "Auditoria SASSMAQ/ISO",
    description: "Sistema de auditoria virtual com certificações SASSMAQ, ISO 9001/14001/45001",
    category: "maintenance",
    enabled: true,
    route: "/auditoria-sassmaq",
  },
  {
    slug: "dashboard",
    name: "Dashboard Executivo",
    description: "Visão consolidada da operação com indicadores em tempo real",
    category: "operations",
    enabled: true,
    route: "/dashboard",
  },
  {
    slug: "tms",
    name: "TMS",
    description: "Gestão de transporte, viagens e despacho",
    category: "operations",
    enabled: true,
    route: "/tms",
  },
  {
    slug: "wms",
    name: "WMS",
    description: "Gestão de armazém, inventário e separação",
    category: "operations",
    enabled: true,
    route: "/wms",
  },
  {
    slug: "erp",
    name: "ERP",
    description: "Financeiro, fiscal e processos administrativos integrados",
    category: "business",
    enabled: true,
    route: "/erp",
  },
  {
    slug: "crm",
    name: "CRM",
    description: "Gestão de relacionamento comercial e carteira de clientes",
    category: "business",
    enabled: true,
    route: "/crm",
  },
  {
    slug: "oms",
    name: "OMS",
    description: "Gestão de pedidos e ciclo operacional ponta a ponta",
    category: "operations",
    enabled: true,
    route: "/oms",
  },
  {
    slug: "driver",
    name: "Portal do Motorista",
    description: "Painel operacional para jornada e viagens",
    category: "operations",
    enabled: true,
    route: "/driver",
  },
  {
    slug: "mechanic",
    name: "Portal da Manutenção",
    description: "Execução e acompanhamento de ordens de serviço",
    category: "maintenance",
    enabled: true,
    route: "/mechanic",
  },
  {
    slug: "maintenance-checklist",
    name: "Checklist de Manutenção",
    description: "Inspeções padronizadas e histórico técnico",
    category: "maintenance",
    enabled: true,
    route: "/maintenance-checklist",
  },
  {
    slug: "gate",
    name: "Gate",
    description: "Controle de entrada e saída de veículos",
    category: "operations",
    enabled: true,
    route: "/gate",
  },
  {
    slug: "live-tracking",
    name: "Rastreamento ao Vivo",
    description: "Acompanhamento em tempo real da frota",
    category: "iot",
    enabled: true,
    route: "/live-tracking",
  },
  {
    slug: "install-app",
    name: "Instalador PWA",
    description: "Ativação de experiência mobile instalável",
    category: "dev",
    enabled: true,
    route: "/install-app",
  },
  {
    slug: "control-tower",
    name: "Control Tower",
    description: "Gestão centralizada de eventos operacionais",
    category: "operations",
    enabled: true,
    route: "/control-tower",
  },
  {
    slug: "control-tower-new",
    name: "Control Tower Redesign",
    description: "Nova interface da torre de controle",
    category: "operations",
    enabled: true,
    route: "/control-tower-new",
  },
  {
    slug: "fleet",
    name: "Gestão de Frota",
    description: "Veículos, disponibilidade e performance de ativos",
    category: "operations",
    enabled: true,
    route: "/fleet",
  },
  {
    slug: "journey-management",
    name: "Gestão de Jornada",
    description: "Conformidade de jornada e eventos de viagem",
    category: "operations",
    enabled: true,
    route: "/journey-management",
  },
  {
    slug: "admin",
    name: "Administração",
    description: "Governança da plataforma e parâmetros globais",
    category: "business",
    enabled: true,
    route: "/admin",
  },
  {
    slug: "esg",
    name: "ESG",
    description: "Métricas de sustentabilidade e governança",
    category: "business",
    enabled: true,
    route: "/esg",
  },
  {
    slug: "dre",
    name: "DRE",
    description: "Demonstrativo de resultado e análise financeira",
    category: "finance",
    enabled: true,
    route: "/dre",
  },
  {
    slug: "employees",
    name: "Funcionários",
    description: "Cadastro e gestão de colaboradores",
    category: "business",
    enabled: true,
    route: "/employees",
  },
  {
    slug: "inventory",
    name: "Inventário",
    description: "Estoque de peças e materiais",
    category: "maintenance",
    enabled: true,
    route: "/inventory",
  },
  {
    slug: "documents",
    name: "Documentos",
    description: "Gestão documental e compliance operacional",
    category: "operations",
    enabled: true,
    route: "/documents",
  },
  {
    slug: "oem",
    name: "Biblioteca OEM",
    description: "Catálogo técnico e padrões de manutenção",
    category: "maintenance",
    enabled: true,
    route: "/oem",
  },
  {
    slug: "scm",
    name: "SCM",
    description: "Supply chain e integração de fornecedores",
    category: "operations",
    enabled: true,
    route: "/scm",
  },
  {
    slug: "executive-dashboard",
    name: "Executive Dashboard",
    description: "Painel executivo com visão estratégica",
    category: "business",
    enabled: true,
    route: "/executive-dashboard",
  },
  {
    slug: "users",
    name: "Usuários",
    description: "Gestão de usuários e acessos",
    category: "operations",
    enabled: true,
    route: "/users",
  },
  {
    slug: "payroll",
    name: "Folha de Pagamento",
    description: "Processamento de folha e cálculos periódicos",
    category: "finance",
    enabled: true,
    route: "/payroll",
  },
  {
    slug: "routing",
    name: "Roteirização",
    description: "Planejamento de rotas e janelas de entrega",
    category: "operations",
    enabled: true,
    route: "/routing",
  },
  {
    slug: "partners",
    name: "Parceiros",
    description: "Gestão de rede de parceiros e transportadoras",
    category: "business",
    enabled: true,
    route: "/partners",
  },
  {
    slug: "centros-custo",
    name: "Centros de Custo",
    description: "Estrutura de custos e análise gerencial",
    category: "finance",
    enabled: true,
    route: "/centros-custo",
  },
  {
    slug: "plano-contas",
    name: "Plano de Contas",
    description: "Classificação contábil e padronização financeira",
    category: "finance",
    enabled: true,
    route: "/plano-contas",
  },
  {
    slug: "lancamentos",
    name: "Lançamentos",
    description: "Lançamentos contábeis e financeiros",
    category: "finance",
    enabled: true,
    route: "/lancamentos",
  },
  {
    slug: "accounts-payable",
    name: "Contas a Pagar",
    description: "Gestão de obrigações e vencimentos",
    category: "finance",
    enabled: true,
    route: "/accounts-payable",
  },
  {
    slug: "accounts-receivable",
    name: "Contas a Receber",
    description: "Gestão de recebíveis e inadimplência",
    category: "finance",
    enabled: true,
    route: "/accounts-receivable",
  },
  {
    slug: "folha-pagamento",
    name: "Folha Pagamento Avançada",
    description: "Consolidação e auditoria de folha",
    category: "finance",
    enabled: true,
    route: "/folha-pagamento",
  },
  {
    slug: "executive-report",
    name: "Relatório Executivo",
    description: "Relatórios estratégicos para diretoria",
    category: "business",
    enabled: true,
    route: "/executive-report",
  },
  {
    slug: "export-center",
    name: "Central de Exportação",
    description: "Exportação de dados e relatórios",
    category: "business",
    enabled: true,
    route: "/export-center",
  },
  {
    slug: "eip",
    name: "EIP",
    description: "Integração empresarial e conectores de dados",
    category: "dev",
    enabled: true,
    route: "/eip",
  },
  {
    slug: "innovation",
    name: "Innovation Lab",
    description: "Laboratório de inovação e novos pilotos",
    category: "dev",
    enabled: true,
    route: "/innovation",
  },
  {
    slug: "driver-journey",
    name: "Jornada do Motorista",
    description: "Monitoramento de jornada e compliance",
    category: "operations",
    enabled: true,
    route: "/driver-journey",
  },
  {
    slug: "driver-payroll",
    name: "Folha do Motorista",
    description: "Apuração e cálculo de pagamentos de motoristas",
    category: "finance",
    enabled: true,
    route: "/driver-payroll",
  },
  {
    slug: "demo",
    name: "Ambiente Demo",
    description: "Sandbox de demonstração comercial",
    category: "dev",
    enabled: true,
    route: "/demo",
  },
  {
    slug: "erp-system",
    name: "ERP System",
    description: "Visão integrada de ERP com analytics, estoque, comunicação e configurações",
    category: "business",
    enabled: true,
    route: "/erp-system",
  },
  {
    slug: "sitemap",
    name: "Mapa do Sistema",
    description: "Visualização de todos os módulos e páginas da plataforma",
    category: "dev",
    enabled: true,
    route: "/sitemap",
  },
];
