import { ModuleDef } from "./types";

export const modules: ModuleDef[] = [
  { slug: "dashboard", name: "Dashboard OptiLog", category: "analiticos", description: "Visão geral operacional e KPIs", route: "/dashboard", enabled: true },
  { slug: "driver-app", name: "App Motorista", category: "operacoes", description: "Viagens, checklists e ganhos em tempo real", route: "/driver", enabled: true },
  { slug: "mechanic-hub", name: "Hub Mecânico", category: "manutencao", description: "OS, manutenção, pneus e TPMS", route: "/mechanic", enabled: true },
  { slug: "tms", name: "TMS", category: "logistica", description: "Gestão de CT-e, romaneios e entregas", route: "/tms", enabled: true },
  { slug: "scm", name: "SCM Compras", category: "operacoes", description: "Suprimentos, pedidos e fornecedores", route: "/scm", enabled: true },
  { slug: "payroll", name: "Folha de Pagamento", category: "pessoas", description: "Cálculos, lançamentos e históricos", route: "/payroll", enabled: true },
  { slug: "accounts-receivable", name: "Contas a Receber", category: "financeiro", description: "Faturas, recebimentos e conciliação", route: "/finance/ar", enabled: true },
  { slug: "revenue", name: "Receita & Margem", category: "analiticos", description: "Análises e alertas de receita", route: "/revenue", enabled: true },
  { slug: "control-tower", name: "Torre de Controle", category: "analiticos", description: "Monitoramento operacional em tempo real", route: "/control-tower", enabled: true },
  { slug: "live-tracking", name: "Live Tracking", category: "logistica", description: "Rastreamento de entregas em tempo real", route: "/live-tracking", enabled: true },
  { slug: "vehicle-list", name: "Frota", category: "manutencao", description: "Cadastro e visão de veículos", route: "/fleet", enabled: true },
  { slug: "tire-control", name: "Pneus", category: "manutencao", description: "Controle, recapagem e descarte", route: "/fleet", enabled: true },
  { slug: "maintenance-plans", name: "Planos Preventivos", category: "manutencao", description: "Planos e agendamentos", route: "/fleet", enabled: true },
  { slug: "warehouse", name: "Armazém", category: "operacoes", description: "Estoques e movimentações", route: "/warehouse", enabled: true },
  { slug: "crm", name: "CRM", category: "comercial", description: "Clientes, propostas e contratos", route: "/crm", enabled: true },
  { slug: "partners", name: "Parceiros", category: "comercial", description: "Gestão de parcerias e distribuição", route: "/partners", enabled: true },
  { slug: "approvals", name: "Aprovações", category: "operacoes", description: "Fluxos e autorizações", route: "/approvals", enabled: true },
  { slug: "user-admin", name: "Usuários & Perfis", category: "pessoas", description: "Gestão de usuários e papéis", route: "/users", enabled: true },
  { slug: "install-app", name: "Instalar App", category: "integracoes", description: "PWA instalação e dicas", route: "/install-app", enabled: true },
  { slug: "module-marketplace", name: "Marketplace", category: "integracoes", description: "Catálogo e ativação de módulos", route: "/marketplace", enabled: true },
  { slug: "settings", name: "Configurações", category: "integracoes", description: "Aparência, branding, idioma, domínio", route: "/settings", enabled: true },
  { slug: "developer", name: "Developer", category: "integracoes", description: "Ferramentas e diagnóstico", route: "/developer", enabled: true },
  { slug: "notification-center", name: "Notificações", category: "operacoes", description: "Centro de alertas e mensagens", route: "/notifications", enabled: true },
  { slug: "oem-maintenance", name: "OEM Manutenção", category: "manutencao", description: "Biblioteca e manuais OEM", route: "/oem", enabled: true },
  { slug: "predictive-alerts", name: "Alertas Preditivos", category: "analiticos", description: "Disparo por previsão ML", route: "/revenue", enabled: true },
  { slug: "cost-alerts", name: "Alertas de Custo", category: "financeiro", description: "Monitor de custos e desvios", route: "/mechanic", enabled: true },
  { slug: "tpms", name: "TPMS", category: "manutencao", description: "Leituras e alertas de pressão", route: "/mechanic", enabled: true },
  { slug: "banking", name: "Bancário", category: "financeiro", description: "Extratos e conciliação", route: "/banking", enabled: false },
  { slug: "contracts", name: "Contratos", category: "comercial", description: "Gestão de contratos", route: "/contracts", enabled: false },
  { slug: "routing", name: "Roteirização", category: "logistica", description: "Rotas e matrizes", route: "/routing", enabled: true },
  { slug: "iot-sensors", name: "Sensores IoT", category: "integracoes", description: "Dispositivos e telemetria", route: "/iot", enabled: false },
  { slug: "quality", name: "Qualidade", category: "operacoes", description: "Auditorias e conformidade", route: "/quality", enabled: false },
  { slug: "ehs", name: "EHS", category: "operacoes", description: "Saúde, segurança e ambiente", route: "/ehs", enabled: true },
  { slug: "leads", name: "Leads", category: "comercial", description: "Captação e funil", route: "/leads", enabled: false },
  { slug: "pricing", name: "Precificação", category: "comercial", description: "Simulador de preços", route: "/pricing", enabled: false },
  { slug: "billing", name: "Faturamento", category: "financeiro", description: "Emissão e fluxo de faturamento", route: "/billing", enabled: false },
  { slug: "costing", name: "Custos", category: "financeiro", description: "Apuração e rateios", route: "/costing", enabled: false },
  { slug: "kpi", name: "KPI", category: "analiticos", description: "Indicadores e metas", route: "/logistics-kpi", enabled: true },
  { slug: "inventory", name: "Inventário", category: "operacoes", description: "Contagens e ajustes", route: "/warehouse", enabled: true },
  { slug: "cold-chain", name: "Cold Chain", category: "logistica", description: "Temperatura e rastreio", route: "/cold-chain", enabled: false },
  { slug: "medications", name: "Medicamentos", category: "operacoes", description: "Registro e lote", route: "/meds", enabled: false },
  { slug: "hazmat", name: "Químicos", category: "operacoes", description: "Regras e segurança", route: "/hazmat", enabled: false },
  { slug: "audits", name: "Auditorias", category: "operacoes", description: "Planos e achados", route: "/audits", enabled: false },
  { slug: "service-catalog", name: "Catálogo de Serviços", category: "comercial", description: "Ofertas e SLAs", route: "/services", enabled: false },
  { slug: "n8n", name: "n8n Workflows", category: "integracoes", description: "Gatilhos e webhooks", route: "/integrations/n8n", enabled: true },
  { slug: "whatsapp", name: "WhatsApp", category: "integracoes", description: "Envio e alertas", route: "/integrations/whatsapp", enabled: false },
  { slug: "ml", name: "ML Insights", category: "analiticos", description: "Modelos e previsões", route: "/revenue", enabled: true },
  { slug: "forms", name: "Formulários", category: "operacoes", description: "Coletas e questionários", route: "/forms", enabled: false },
  { slug: "docs", name: "Documentos", category: "operacoes", description: "Arquivos e versões", route: "/documents", enabled: true },
  { slug: "notifications", name: "Notificações", category: "operacoes", description: "Mensagens e canais", route: "/notifications", enabled: true },
  { slug: "settings-appearance", name: "Aparência", category: "integracoes", description: "Tema e branding", route: "/settings/appearance", enabled: true },
  { slug: "settings-domain", name: "Domínio", category: "integracoes", description: "Configuração de domínio", route: "/settings/domain", enabled: true }
];
