// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both Vite (import.meta.env) and Next.js (process.env) environments
const getEnvVar = (viteKey: string, nextKey: string): string | undefined => {
  // Try Next.js style first (process.env)
  if (typeof process !== 'undefined' && process.env) {
    const nextValue = process.env[nextKey];
    if (nextValue) return nextValue;
  }
  // Fall back to Vite style (import.meta.env)
  if (typeof import.meta !== 'undefined' && import.meta.env) {
    return import.meta.env[viteKey] as string | undefined;
  }
  return undefined;
};

const rawUrl = getEnvVar('VITE_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_URL');
const rawKeyAnon = getEnvVar('VITE_SUPABASE_ANON_KEY', 'NEXT_PUBLIC_SUPABASE_ANON_KEY');
const rawKeyPub = getEnvVar('VITE_SUPABASE_PUBLISHABLE_KEY', 'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY');
const rawKey = rawKeyPub ?? rawKeyAnon;

// Sanitize and validate envs to prevent common issues (backticks, spaces, placeholders)
// Also strip accidental surrounding quotes ("..." or '...') in addition to backticks
const SUPABASE_URL = (rawUrl || '')
  .trim()
  .replace(/^`|`$/g, '')
  .replace(/^"|"$/g, '')
  .replace(/^'|'$/g, '');
const SUPABASE_PUBLISHABLE_KEY = (rawKey || '')
  .trim()
  .replace(/^`|`$/g, '')
  .replace(/^"|"$/g, '')
  .replace(/^'|'$/g, '');

if (!SUPABASE_URL || SUPABASE_URL.includes('SEU-PROJETO')) {
  console.error('[Supabase] VITE_SUPABASE_URL inválida ou placeholder. Atualize .env.local com a URL real.');
}
if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.includes('REPLACE_ME')) {
  console.error('[Supabase] VITE_SUPABASE_ANON_KEY/VITE_SUPABASE_PUBLISHABLE_KEY inválida ou placeholder. Use sua anon/publishable key real.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const HAS_ENV = !!SUPABASE_URL && !!SUPABASE_PUBLISHABLE_KEY;
let _supabase: any;
if (HAS_ENV) {
  _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: { storage: localStorage, persistSession: true, autoRefreshToken: true }
  });
} else {
  const err = (msg: string) => Promise.resolve({ data: null, error: new Error(msg) });
  const tableOps = {
    select: () => err('Supabase não configurado'),
    insert: () => err('Supabase não configurado'),
    update: () => err('Supabase não configurado'),
    delete: () => err('Supabase não configurado'),
    eq: () => tableOps,
    order: () => tableOps,
    limit: () => tableOps,
  } as any;
  _supabase = {
    from: () => tableOps,
    auth: {
      onAuthStateChange: (cb: any) => {
        try { cb('SIGNED_OUT', null); } catch {}
        return { data: { subscription: { unsubscribe() {} } } };
      },
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: new Error('Supabase não configurado') }),
      signUp: () => Promise.resolve({ data: { user: null, session: null }, error: new Error('Supabase não configurado') }),
      signOut: () => Promise.resolve({ error: null }),
      getUser: () => err('Supabase não configurado')
    }
  };
}
export const supabase = _supabase as ReturnType<typeof createClient<Database>>;

// Runtime diagnostic: verify that the key matches the project ref in URL
try {
  const host = new URL(SUPABASE_URL).host; // e.g., eixkv...supabase.co
  const projectRef = host.split('.supabase.co')[0];

  const parts = SUPABASE_PUBLISHABLE_KEY.split('.');
  if (parts.length === 3) {
    const payloadBase64 = parts[1].replace(/-/g, '+').replace(/_/g, '/');
    const padded = payloadBase64 + '='.repeat((4 - (payloadBase64.length % 4)) % 4);
    const payloadJson = JSON.parse(atob(padded));
    const ref = payloadJson?.ref;
    const role = payloadJson?.role;

    if (ref && ref !== projectRef) {
      console.error(`[Supabase] A chave pertence ao projeto '${ref}', mas a URL aponta para '${projectRef}'. Atualize .env.local com a chave correta do mesmo projeto.`);
    }
    if (role && role !== 'anon') {
      console.warn(`[Supabase] A chave usada tem role '${role}'. Para frontend, use a chave public/anon do projeto.`);
    }
  }
} catch {
}
